# Generated by Django 5.1 on 2024-11-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0003_alter_question_correct_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_screen', models.BooleanField(default=True, help_text='Indicates if screen capture is enabled', verbose_name='Capture Screen')),
                ('tab_switch', models.BooleanField(default=True, help_text='Indicates if tab switch monitoring is enabled', verbose_name='Tab Switch')),
                ('tab_switch_limit', models.IntegerField(help_text='Maximum allowable tab switches during the exam', verbose_name='Tab Switch Limit')),
                ('browser_activity', models.BooleanField(default=True, help_text='Indicates if browser activity monitoring is enabled', verbose_name='Browser Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('exam_status', models.CharField(max_length=50)),
                ('random_order', models.BooleanField()),
                ('copy_paste_restrict', models.BooleanField()),
                ('total_question', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('total_attempt', models.IntegerField()),
                ('question_list', models.JSONField(blank=True, null=True)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionbank')),
                ('tracking_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.trackingsetting')),
            ],
        ),
    ]
