# Generated by Django 5.1 on 2024-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(default='Exam', max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_status',
            field=models.CharField(default='unavailable', max_length=50),
        ),
    ]
