# Generated by Django 5.1 on 2024-11-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_title_alter_exam_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='year_sem',
            field=models.CharField(default=2.0, max_length=50),
            preserve_default=False,
        ),
    ]
