# Generated by Django 5.1 on 2024-11-10 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_year_sem'),
        ('user', '0007_course_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='lecturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.lecturer'),
            preserve_default=False,
        ),
    ]
