# Generated by Django 5.1 on 2024-11-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingsetting',
            name='browser_activity',
            field=models.BooleanField(default=False, help_text='Indicates if browser activity monitoring is enabled', verbose_name='Browser Activity'),
        ),
        migrations.AlterField(
            model_name='trackingsetting',
            name='capture_screen',
            field=models.BooleanField(default=False, help_text='Indicates if screen capture is enabled', verbose_name='Capture Screen'),
        ),
        migrations.AlterField(
            model_name='trackingsetting',
            name='tab_switch',
            field=models.BooleanField(default=False, help_text='Indicates if tab switch monitoring is enabled', verbose_name='Tab Switch'),
        ),
        migrations.AlterField(
            model_name='trackingsetting',
            name='tab_switch_limit',
            field=models.IntegerField(default=0, help_text='Maximum allowable tab switches during the exam', verbose_name='Tab Switch Limit'),
        ),
    ]
