# Generated by Django 5.1 on 2024-11-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_trackingsetting_browser_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_status',
            field=models.BooleanField(default=True),
        ),
    ]
