# Generated by Django 5.1 on 2025-01-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_exam_exam_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='tracking_setting',
        ),
        migrations.AddField(
            model_name='trackingsetting',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
            preserve_default=False,
        ),
    ]
