# Generated by Django 5.1 on 2025-01-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_exam_tracking_setting_trackingsetting_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='year_sem',
            new_name='cohort',
        ),
    ]
