# Generated by Django 5.1 on 2025-01-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='introduction',
            field=models.TextField(default='we'),
            preserve_default=False,
        ),
    ]
