# Generated by Django 5.1 on 2025-01-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0006_alter_exam_exam_status'),
        ('user', '0012_remove_lecturer_email_remove_lecturer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graded', models.BooleanField(default=True, verbose_name='Status of the completed exam (e.g., graded=False, ungraded=True)')),
                ('attempt', models.PositiveIntegerField(verbose_name='Attempt number of the completed exam')),
                ('total_mark', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total marks obtained in the completed exam')),
                ('full_mark', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total marks of the exam')),
                ('time_taken', models.PositiveIntegerField(verbose_name='Duration of time taken to complete the exam')),
                ('answers', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments or feedback on the completed exam')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Identifier linking to the original exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='Identifier linking to the student who took the exam')),
            ],
            options={
                'verbose_name': 'Completed Exam',
                'verbose_name_plural': 'Completed Exams',
            },
        ),
        migrations.CreateModel(
            name='ScreenCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(upload_to='')),
                ('completed_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='completed_exam.completedexam')),
            ],
        ),
    ]
