# Generated by Django 5.1 on 2025-01-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screencapture',
            name='location',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
