# Generated by Django 5.1 on 2025-01-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_exam', '0002_alter_screencapture_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_log', models.JSONField()),
                ('completed_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='completed_exam.completedexam')),
            ],
        ),
    ]
