# Generated by Django 5.1 on 2025-01-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completed_exam', '0003_examactivity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamActivity',
            new_name='BrowserActivity',
        ),
    ]
