# Generated by Django 5.1 on 2025-01-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_exam', '0004_rename_examactivity_browseractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexam',
            name='essay_marks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
