# Generated by Django 5.1 on 2025-01-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_exam', '0005_completedexam_essay_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedexam',
            name='answers',
            field=models.JSONField(blank=True, null=True, verbose_name='Marks of each indivisual essay question if exist'),
        ),
    ]
