# Generated by Django 5.1 on 2025-01-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completed_exam', '0006_alter_completedexam_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedexam',
            old_name='essay_marks',
            new_name='essay_mark',
        ),
    ]
