# Generated by Django 5.1 on 2025-01-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_exam', '0007_rename_essay_marks_completedexam_essay_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexam',
            name='exam_passed',
            field=models.BooleanField(default=True, verbose_name='Pass status, Pass or Fail'),
        ),
    ]
