# Generated by Django 5.1 on 2024-11-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_remove_lecturer_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('option', models.JSONField()),
                ('correct_answer', models.JSONField()),
                ('marks', models.PositiveIntegerField()),
                ('explanation', models.TextField()),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionbank')),
            ],
        ),
    ]
