# Generated by Django 5.1 on 2025-01-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_correct_answers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option',
            new_name='options',
        ),
    ]
