# Generated by Django 5.1 on 2024-10-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_course_alter_student_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='course',
        ),
    ]
