# Generated by Django 5.1 on 2024-10-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_faculty_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='course',
        ),
    ]
