# Generated by Django 5.1 on 2024-11-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_course_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='user.lecturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='registered_courses',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.programme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.programme'),
            preserve_default=False,
        ),
    ]
