# Generated by Django 5.1 on 2024-11-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_student_email_remove_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
