# Generated by Django 5.1 on 2025-01-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_lecturer_email_remove_lecturer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year_sem',
            new_name='cohort',
        ),
    ]
